
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Viraad
 */
public class revenue extends javax.swing.JFrame {
revenueshop rs = new revenueshop();
database db = new database();
revenueamuesment ra = new revenueamuesment();
    /**
     * Creates new form revenue
     */
    public revenue() {
        initComponents();
        this.getContentPane().setBackground(new Color(51,51,51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        revenueshop = new javax.swing.JToggleButton();
        revenueamuesment = new javax.swing.JButton();
        totalrevenue = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Revenue");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Revenue Generated by the date");

        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("is as follows");

        revenueshop.setBackground(new java.awt.Color(160, 90, 199));
        revenueshop.setText("Revenue by Shops");
        revenueshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueshopActionPerformed(evt);
            }
        });

        revenueamuesment.setBackground(new java.awt.Color(160, 90, 199));
        revenueamuesment.setText("Revenue By Amuesment Park");
        revenueamuesment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revenueamuesmentActionPerformed(evt);
            }
        });

        totalrevenue.setBackground(new java.awt.Color(160, 90, 199));
        totalrevenue.setText("Total Revenue");
        totalrevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalrevenueActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(160, 90, 199));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(totalrevenue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(revenueshop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(revenueamuesment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backbtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(revenueshop)
                .addGap(18, 18, 18)
                .addComponent(revenueamuesment)
                .addGap(18, 18, 18)
                .addComponent(totalrevenue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void revenueshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueshopActionPerformed
    try {
        // TODO add your handling code here:
        new revenueshop().setVisible(true);
        String query = "select shop_name,owner_name,rent from shop";
        db.st = db.con.createStatement();
        db.rs = db.st.executeQuery(query);
        while (db.rs.next()){
            
            String shopname = db.rs.getString("shop_name");
            String ownername = db.rs.getString("owner_name");
            double rent = db.rs.getDouble("rent");
            Object tbData [] = {shopname,ownername,rent};
            // DefaultTableModel tbl = (DefaultTableModel)jTable1.getModel();
            DefaultTableModel  tbl = (DefaultTableModel)rs.jTable1.getModel();
            tbl.addRow(tbData);
        }
    }catch (SQLException ex) {
        Logger.getLogger(revenue.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_revenueshopActionPerformed

    private void revenueamuesmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revenueamuesmentActionPerformed
        // TODO add your handling code here:
       try {
        // TODO add your handling code here:
        new revenueshop().setVisible(true);
        String query = "select ride_name,ticket_price,total_fare from ride_start";
        db.st = db.con.createStatement();
        db.rs = db.st.executeQuery(query);
        while (db.rs.next()){
            
            String ride_name = db.rs.getString("ride_name");
            String ticket_price = db.rs.getString("ticket_price");
            //System.out.println(ticket_price);
            double totalfare = db.rs.getDouble("total_fare");
            Object tbData [] = {ride_name,ticket_price,totalfare};
            // DefaultTableModel tbl = (DefaultTableModel)jTable1.getModel();
            DefaultTableModel  tbl = (DefaultTableModel)ra.jTable1.getModel();
            tbl.addRow(tbData);
        }
    }catch (SQLException ex) {
        Logger.getLogger(revenue.class.getName()).log(Level.SEVERE, null, ex);
    } 
        
        
    }//GEN-LAST:event_revenueamuesmentActionPerformed
double totalsumride;
double totalsumshop;
    private void totalrevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalrevenueActionPerformed
    try {                                             
        try {
            // TODO add your handling code here:
            
            
            String query = "select total_fare from ride_start";
            db.st = db.con.createStatement();
            db.rs = db.st.executeQuery(query);
            while (db.rs.next()){
                double sum1 = db.rs.getDouble("total_fare");
                totalsumride+=sum1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(revenue.class.getName()).log(Level.SEVERE, null, ex);
        }
        String query2 = "select rent from shop";
        db.st = db.con.createStatement();
        db.rs = db.st.executeQuery(query2);
        while (db.rs.next()){
            double sum2 = db.rs.getDouble("rent");
            totalsumshop+=sum2;
        }
        
        
    } catch (SQLException ex) {
        Logger.getLogger(revenue.class.getName()).log(Level.SEVERE, null, ex);
    }
    double totalfinal = totalsumshop + totalsumride;
    JOptionPane.showMessageDialog(this, "The total revenue generated is: "+totalfinal);
    
    }//GEN-LAST:event_totalrevenueActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        new finance().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backbtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new revenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton revenueamuesment;
    private javax.swing.JToggleButton revenueshop;
    private javax.swing.JButton totalrevenue;
    // End of variables declaration//GEN-END:variables
}
